site_name: Jiu-Jitsu
site_description: Documentação Oficial do Projeto Jiu
site_url: https://projetosjc.github.io/Jiu-Jitsu/
site_author: Jiu-Jitsu Team
repo_name: Jiu-Jitsu
repo_url: https://projetosjc.github.io/Jiu-Jitsu/
edit_uri: edit/docs/docs/

theme:
  name: material
  language: pt-BR
  custom_dir: overrides
  logo: assets/logo.png  # Adiciona o logo
  favicon: assets/logoJJ.ico  # Adiciona o favicon
  features:
    - content.code.annotation
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - content.code.copy
# Paleta
  palette:
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "teal"
      accent: "brown"
      toggle:
        icon: material/weather-night
        name: Mudar para o tema escuro
    # Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "teal"
      accent: "brown"
      toggle:
        icon: material/weather-sunny
        name: Mudar para o tema claro
  
# For image rendering
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - glightbox:
       touchNavigation: true
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       caption_position: bottom

nav:
  - Início: index.md
  - Visão do Produto e Projeto:
      - Cenário Atual do Cliente e do Negócio: visao/1-cenario.md
      - Solução Proposta: visao/2-solucao.md
      - Estratégias de Engenharia de Software: visao/3-estrategia.md
      - Engenharia de Requisitos: visao/4-engenharia.md #nova aba
      - Cronogramas e Entregas: visao/5-cronograma.md
      - Interação Entre Equipe e Cliente: visao/6-interacao.md
      - Requisitos de Software: visao/7-requisitos.md #nova aba
      - DoR e DoD: visao/8-dor-e-dod.md #nova aba
      - Backlog de Produto: visao/9-backlog.md #nova aba


# Extra CSS
extra_css:
  - extra.css  # Arquivo CSS customizado